account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    
    path('login/', views.user_login, name='login'),
    
    path('logout/', views.user_logout, name='logout'),
    
    path('my_profile/', views.my_profile, name='my_profile'),
    
    path('view_profile/<int:user_id>/', views.view_profile, name='view_profile'),
    
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    
    path('users/', views.user_list, name='user_list'),
    
    path('update_user_type/<int:user_id>/', views.update_user_type, name='update_user_type'),
    
    path('change_verification_status/<int:profile_id>/', views.change_verification_status, name='change_verification_status'),
    
    path('ajax/load-departments/', views.load_departments, name='ajax_load_departments'), # AJAX for dependant dropdown
    
    path('social-auth/', include('social_django.urls', namespace='social')), # for google auth
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    
    # path('university/', include('university.urls')),
]

onebyzero_edu/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('study/', include('study.urls')),
    path('account/', include('account.urls')),
    path('core/', include('core.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
# from study.models import Department, University


class Profile(models.Model):
    USER_TYPE_CHOICES = (
        ('student', 'Student'),
        ('batch_ambassador', 'Batch Ambassador'),
        ('departmental_ambassador', 'Departmental Ambassador'),
        ('university_ambassador', 'University Ambassador'),
        ('admin', 'Admin'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=100, choices=USER_TYPE_CHOICES, default='student')
    # is_departmental_ambassador = models.ForeignKey('study.Department', on_delete=models.CASCADE, blank=True, null=True)
    bio = models.TextField(blank=True)
    fullname = models.CharField(max_length=100, blank=True)
    nickname = models.CharField(max_length=100, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True)
    university = models.ForeignKey('study.University', on_delete=models.CASCADE, blank=True, null=True)
    department = models.ForeignKey('study.Department', on_delete=models.CASCADE, blank=True, null=True)
    year = models.PositiveIntegerField(blank=True, null=True)
    semester = models.PositiveIntegerField(blank=True, null=True)
    is_verified = models.BooleanField(default=False)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile
from study.models import University, Department


# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from study.models import University, Department
from .models import User, Profile

class SignupForm(UserCreationForm):
    university = forms.ModelChoiceField(queryset=University.objects.all(), required=True)
    department = forms.ModelChoiceField(queryset=Department.objects.all(), required=False)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']  # Include other fields from the User model

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['university'].label = 'University'
        self.fields['department'].label = 'Department'

        if all(field in self.data for field in ['university', 'department']):
            try:
                university_id = int(self.data.get('university'))
                department_id = int(self.data.get('department'))
                
                # Filter the 'department' queryset based on the selected 'university'.
                self.fields['department'].queryset = Department.objects.filter(university_id=university_id).order_by('name')

            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['department'].queryset = self.instance.university.department_set.order_by('name')
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()

        # Create a Profile instance and associate it with the user
        profile = Profile.objects.create(user=user, university=self.cleaned_data['university'], department=self.cleaned_data['department'])

        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user', 'bio', 'user_type', 'profile_image', 'email', 'university', 'department', 'year', 'semester']


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =  ['bio', 'user_type', 'profile_image', 'email', 'university', 'department', 'year', 'semester']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['department'].queryset = Department.objects.none()

        if 'university' in self.data:
            try:
                university_id = int(self.data.get('university'))
                self.fields['department'].queryset = Department.objects.filter(university_id=university_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance and self.instance.university: 
            self.fields['department'].queryset = self.instance.university.department_set.order_by('name')

account/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from .forms import SignupForm, LoginForm, ProfileForm, EditProfileForm
from django.contrib.auth.decorators import login_required
from . models import Profile
from django.contrib.auth.models import User
from study.models import Department, Course
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')  # Log the user in after registration
            # UserProfile.objects.create(user=user)
            return redirect('home')  # Redirect to the user's profile page
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('my_department', university_id=1, department_id=1)
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login')


# PROFILE VIEWS =============================
@login_required
def my_profile(request):
    # Assuming the user is logged in
    user = request.user
    
    try:
        profile = Profile.objects.get(user=user)  # Retrieve the user's profile
    except Profile.DoesNotExist:
         # If the profile doesn't exist, create a new one
        profile = Profile(user=user)
        profile.save()
        # You can also redirect the user to an edit profile page to fill in details
        return redirect('my_profile')
    
    context = {
        'profile': profile
    }

    return render(request, 'profile/my_profile.html', context)

from study.models import *
@login_required
def view_profile(request, user_id):
    # Retrieve the user based on user_id, or return a 404 if not found
    user = get_object_or_404(User, id=user_id)
    
    try:
        profile = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        # If the profile doesn't exist, you can handle it as needed
        # For example, you might want to create a new profile or redirect to a page
        # return render(request, 'profile/profile_not_found.html')
        pass
    
    # QUESTIONS ========================================
    qs_sem1 = Question.objects.filter(uploaded_by=user, course__year=1, course__semester=1).count()
    
    qs_sem2 = Question.objects.filter(uploaded_by=user, course__year=1, course__semester=2).count()
    
    qs_sem3 = Question.objects.filter(uploaded_by=user, course__year=2, course__semester=1).count()
    
    qs_sem4 = Question.objects.filter(uploaded_by=user, course__year=2, course__semester=2).count()
    
    qs_sem5 = Question.objects.filter(uploaded_by=user, course__year=3, course__semester=1).count()
    
    qs_sem6 = Question.objects.filter(uploaded_by=user, course__year=3, course__semester=2).count()
    
    qs_sem7 = Question.objects.filter(uploaded_by=user, course__year=4, course__semester=1).count()
    
    qs_sem8 = Question.objects.filter(uploaded_by=user, course__year=4, course__semester=2).count()
    
    qs_total = qs_sem1 + qs_sem2 + qs_sem3 + qs_sem4 + qs_sem5 + qs_sem6 + qs_sem7 + qs_sem8
    

# BOOKS ==============================================
    books_sem1 = BookModel.objects.filter(uploaded_by=user, course__year=1, course__semester=1).count()
    
    books_sem2 = BookModel.objects.filter(uploaded_by=user, course__year=1, course__semester=2).count()
    
    books_sem3 = BookModel.objects.filter(uploaded_by=user, course__year=2, course__semester=1).count()
    
    books_sem4 = BookModel.objects.filter(uploaded_by=user, course__year=2, course__semester=2).count()
    
    books_sem5 = BookModel.objects.filter(uploaded_by=user, course__year=3, course__semester=1).count()
    
    books_sem6 = BookModel.objects.filter(uploaded_by=user, course__year=3, course__semester=2).count()
    
    books_sem7 = BookModel.objects.filter(uploaded_by=user, course__year=4, course__semester=1).count()
    
    books_sem8 = BookModel.objects.filter(uploaded_by=user, course__year=4, course__semester=2).count()
    
    books_total = books_sem1 + books_sem2 + books_sem3 + books_sem4 + books_sem5 + books_sem6 + books_sem7 + books_sem8
    

# LECTURE SLIDES ============================================
    lectures_sem1 = LectureModel.objects.filter(uploaded_by=user, course__year=1, course__semester=1).count()
    
    lectures_sem2 = LectureModel.objects.filter(uploaded_by=user, course__year=1, course__semester=2).count()
    
    lectures_sem3 = LectureModel.objects.filter(uploaded_by=user, course__year=2, course__semester=1).count()
    
    lectures_sem4 = LectureModel.objects.filter(uploaded_by=user, course__year=2, course__semester=2).count()
    
    lectures_sem5 = LectureModel.objects.filter(uploaded_by=user, course__year=3, course__semester=1).count()
    
    lectures_sem6 = LectureModel.objects.filter(uploaded_by=user, course__year=3, course__semester=2).count()
    
    lectures_sem7 = LectureModel.objects.filter(uploaded_by=user, course__year=4, course__semester=1).count()
    
    lectures_sem8 = LectureModel.objects.filter(uploaded_by=user, course__year=4, course__semester=2).count()
    
    lectures_total = lectures_sem1 + lectures_sem2 + lectures_sem3 + lectures_sem4 + lectures_sem5 + lectures_sem6 + lectures_sem7 + lectures_sem8
    
    
# NOTES =============================================
    notes_sem1 = BookModel.objects.filter(uploaded_by=user, course__year=1, course__semester=1).count()
    
    notes_sem2 = BookModel.objects.filter(uploaded_by=user, course__year=1, course__semester=2).count()
    
    notes_sem3 = BookModel.objects.filter(uploaded_by=user, course__year=2, course__semester=1).count()
    
    notes_sem4 = BookModel.objects.filter(uploaded_by=user, course__year=2, course__semester=2).count()
    
    notes_sem5 = BookModel.objects.filter(uploaded_by=user, course__year=3, course__semester=1).count()
    
    notes_sem6 = BookModel.objects.filter(uploaded_by=user, course__year=3, course__semester=2).count()
    
    notes_sem7 = BookModel.objects.filter(uploaded_by=user, course__year=4, course__semester=1).count()
    
    notes_sem8 = BookModel.objects.filter(uploaded_by=user, course__year=4, course__semester=2).count()
    
    notes_total = notes_sem1 + notes_sem2 + notes_sem3 + notes_sem4 + notes_sem5 + notes_sem6 + notes_sem7 + notes_sem8
    
    # TOTAL UPLOADS ==================
    total_uploads = sum([qs_total, books_total, lectures_total, notes_total], 0)
    
    # TOTALS UPLOADS SEMESTER WISE
    all_sem1 = sum([qs_sem1, books_sem1, lectures_sem1, notes_sem1], 0)
    all_sem2 = sum([qs_sem2, books_sem2, lectures_sem2, notes_sem2], 0)
    all_sem3 = sum([qs_sem3, books_sem3, lectures_sem3, notes_sem3], 0)
    all_sem4 = sum([qs_sem4, books_sem4, lectures_sem4, notes_sem4], 0)
    all_sem5 = sum([qs_sem5, books_sem5, lectures_sem5, notes_sem5], 0)
    all_sem6 = sum([qs_sem6, books_sem6, lectures_sem6, notes_sem6], 0)
    all_sem7 = sum([qs_sem7, books_sem7, lectures_sem7, notes_sem7], 0)
    all_sem8 = sum([qs_sem8, books_sem8, lectures_sem8, notes_sem8], 0)
    

    context = {
        'profile': profile,
        'viewed_user': user,
        
        'qs_sem1': qs_sem1,
        'qs_sem2': qs_sem2,
        'qs_sem3': qs_sem3,
        'qs_sem4': qs_sem4,
        'qs_sem5': qs_sem5,
        'qs_sem6': qs_sem6,
        'qs_sem7': qs_sem7,
        'qs_sem8': qs_sem8,
        'qs_total': qs_total,
        
        'books_sem1': books_sem1,
        'books_sem2': books_sem2,
        'books_sem3': books_sem3,
        'books_sem4': books_sem4,
        'books_sem5': books_sem5,
        'books_sem6': books_sem6,
        'books_sem7': books_sem7,
        'books_sem8': books_sem8,
        'books_total': books_total,
        
        'lectures_sem1': lectures_sem1,
        'lectures_sem2': lectures_sem2,
        'lectures_sem3': lectures_sem3,
        'lectures_sem4': lectures_sem4,
        'lectures_sem5': lectures_sem5,
        'lectures_sem6': lectures_sem6,
        'lectures_sem7': lectures_sem7,
        'lectures_sem8': lectures_sem8,
        'lectures_total': lectures_total,
        
        'notes_sem1': notes_sem1,
        'notes_sem2': notes_sem2,
        'notes_sem3': notes_sem3,
        'notes_sem4': notes_sem4,
        'notes_sem5': notes_sem5,
        'notes_sem6': notes_sem6,
        'notes_sem7': notes_sem7,
        'notes_sem8': notes_sem8,
        'notes_total': notes_total,
        
        'total_uploads': total_uploads,
        
        'all_sem1': all_sem1,
        'all_sem2': all_sem2,
        'all_sem3': all_sem3,
        'all_sem4': all_sem4,
        'all_sem5': all_sem5,
        'all_sem6': all_sem6,
        'all_sem7': all_sem7,
        'all_sem8': all_sem8,
    }

    return render(request, 'profile/view_profile.html', context)


@login_required
def edit_profile(request):
    user = request.user

    try:
        profile = Profile.objects.get(user=user)  # Retrieve the user's profile
    except Profile.DoesNotExist:
        # If the profile doesn't exist, create a new one
        profile = Profile(user=user)
        profile.save()
    
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('my_profile')

Final/onebyzero_edu/account/templates/profile/view_profile.html
<!-- profile.html -->
{% extends "base.html" %}
{% block content %}

<div class="container mt-4">
    <div class="row">
    
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h2>User Profile</h2>
                        <a href="{% url 'edit_profile' %}">
                            <i class="fas fa-edit"></i> Edit
                        </a>
                    </div>

                    <div class="profile-section">
                        {% if profile.profile_image %}
                        <div class="profile-image-container">
                            <img src="{{ profile.profile_image.url }}" alt="Profile Image" class="profile-image" style="width: 150px;">
                        </div>
                        {% endif %}

                        <div class="profile-details">
                            <h5 class="card-title">Profile Information</h5>
                            <p><strong>Username:</strong> {{ profile.user.username }}</p>
                            <p><strong>User Type:</strong> {{ profile.get_user_type_display }}</p>
                            <p><strong>Bio:</strong> {{ profile.bio }}</p>
                            <p><strong>Email:</strong> {{ profile.email }}</p>
                            <p><strong>Department:</strong> {{ profile.department }}</p>
                            <p><strong>University:</strong> {{ profile.university }}</p>
                            <p><strong>Year:</strong> {{ profile.year }}</p>
                            <p><strong>Semester:</strong> {{ profile.semester }}</p>
                            <p><strong>Is Verified: </strong>{{ profile.is_verified }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-3">
                <a href="#" class="btn btn-primary">Change Password</a>
            </div>
        </div>

        <div class="col-md-9">
            
            <h5>Total Uploads: {{total_uploads}}</h5>

            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">1st Sem</th>
                    <th scope="col">2nd Sem</th>
                    <th scope="col">3rd Sem</th>
                    <th scope="col">4th Sem</th>
                    <th scope="col">5th Sem</th>
                    <th scope="col">6th Sem</th>
                    <th scope="col">7th Sem</th>
                    <th scope="col">8th Sem</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">Questions</th>
                    <td> {{ qs_sem1 }}</td>
                    <td>{{ qs_sem2 }}</td>
                    <td>{{ qs_sem3 }}</td>
                    <td>{{ qs_sem4 }}</td>
                    <td>{{ qs_sem5 }}</td>
                    <td>{{ qs_sem6 }}</td>
                    <td>{{ qs_sem7 }}</td>
                    <td>{{ qs_sem8 }}</td>
                   <td><strong>{{ qs_total }}</strong></td>
                  </tr>

                  <tr>
                    <th scope="row">Books</th>
                    <td>{{books_sem1}}</td>
                    <td>{{books_sem2}}</td>
                    <td>{{books_sem3}}</td>
                    <td>{{books_sem4}}</td>
                    <td>{{books_sem5}}</td>
                    <td>{{books_sem6}}</td>
                    <td>{{books_sem7}}</td>
                    <td>{{books_sem8}}</td>
                    <td><strong>{{books_total}}</strong></td>
                  </tr>

                  <tr>
                    <th scope="row">Notes</th>
                    <td>{{notes_sem1}}</td>
                    <td>{{notes_sem2}}</td>
                    <td>{{notes_sem3}}</td>
                    <td>{{notes_sem4}}</td>
                    <td>{{notes_sem5}}</td>
                    <td>{{notes_sem6}}</td>
                    <td>{{notes_sem7}}</td>
                    <td>{{notes_sem8}}</td>
                    <td><strong>{{notes_total}}</strong></td>
              
                  </tr>

                  <tr>
                    <th scope="row">Lecture Slides</th>
                    <td>{{lectures_sem1}}</td>
                    <td>{{lectures_sem2}}</td>
                    <td>{{lectures_sem3}}</td>
                    <td>{{lectures_sem4}}</td>
                    <td>{{lectures_sem5}}</td>
                    <td>{{lectures_sem6}}</td>
                    <td>{{lectures_sem7}}</td>
                    <td>{{lectures_sem8}}</td>
                    <td><strong>{{lectures_total}}</strong></td>
                  </tr>

                <tr>
                    <th scope="row">Total</th>
                    <td><strong>{{all_sem1}}<strong/></td>
                    <td><strong>{{all_sem2}}<strong/></td>
                    <td><strong>{{all_sem3}}<strong/></td>
                    <td><strong>{{all_sem4}}<strong/></td>
                    <td><strong>{{all_sem5}}<strong/></td>
                    <td><strong>{{all_sem6}}<strong/></td>
                    <td><strong>{{all_sem7}}<strong/></td>
                    <td><strong>{{all_sem8}}<strong/></td>
                    <td><strong>{{total_uploads}}<strong/></td>
                  </tr>
                  
                </tbody>
              </table>

        {% comment %} 
            <h5>Questions:</h5>
            <hr>
            <table class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">1st Mid</th>
                    <th scope="col">2nd Mid</th>
                    <th scope="col">3rd Mid</th>
                    <th scope="col">Class Test</th>
                    <th scope="col">Lab Test</th>
                    <th scope="col">Lab Final</th>
                    <th scope="col">Final </th>
                    <th scope="col">Total </th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1st Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">2nd Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">3rd Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">4th Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">5th Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">6th Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">7th Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row">8th Sem</th>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                  </tr>

                  <tr>
                    <th scope="row" colspan="8">Total</th>
                    <td>0</td>
                  </tr>

                </tbody>
              </table>  {% endcomment %}



            {% comment %} <div class="mx-5">
                <p>{% lorem 4 b random %}</p>
            </div> {% endcomment %}

        </div>
    </div>
</div>

{% endblock %}